sudo: required
dist: trusty
cache: bundler

addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk

branches:
  only:
  - master

services: docker

env:
- INSTANCE=default-centos-6
- INSTANCE=default-centos-7
- INSTANCE=default-debian-7
- INSTANCE=default-debian-8
- INSTANCE=default-fedora-latest
- INSTANCE=default-ubuntu-1404
- INSTANCE=default-ubuntu-1604
- INSTANCE=mms-agent-centos-6
- INSTANCE=mms-agent-centos-7
- INSTANCE=mms-agent-ubuntu-1404
- INSTANCE=mms-agent-ubuntu-1604

before_script:
- sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
- eval "$(/opt/chefdk/bin/chef shell-init bash)"
- chef --version
- cookstyle --version
- foodcritic --version
- chef gem install danger

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - chef exec delivery local all
      env: UNIT_AND_LINT=1
