name              'sc-mongodb'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures mongodb'
source_url        'https://github.com/sous-chefs/sc-mongodb'
issues_url        'https://github.com/sous-chefs/sc-mongodb/issues'
chef_version      '>= 15.3'
version           '5.1.21'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'oracle'
supports 'redhat'
supports 'ubuntu'
supports 'rocky'
