# frozen_string_literal: true

name              'sc-mongodb'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides custom resources for installing and configuring MongoDB'
source_url        'https://github.com/sous-chefs/sc-mongodb'
issues_url        'https://github.com/sous-chefs/sc-mongodb/issues'
chef_version      '>= 15.3'
version           '5.1.26'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 20.04'
