name              'sc-mongodb'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs and configures mongodb'
source_url        'https://github.com/sous-chefs/mongodb'
issues_url        'https://github.com/sous-chefs/mongodb/issues'
chef_version      '>= 14.0'
version           '4.1.1'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'oracle'
supports 'redhat'
supports 'ubuntu'
